### ISSUE TITLE
任务依赖功能没有实现吧

### ISSUE THREAD

**Issue by FireEyeMamba** [ihaolin/antares#12]
`if (instance != null && finished){
                jobSupport.checkJobInstanceFinish(shardFinishDto);
            }`

检查是否job instance完成的时候并没有触发下游啊

**Comment by ihaolin** [comment]
这个是通过事件通知去触发的，可以看下：
DefaultJobExecutor.java：
![image](https://user-images.githubusercontent.com/8662695/34402551-420a96d8-ebdd-11e7-8cad-b5ff4342b044.png)
JobEventListener.java：
![image](https://user-images.githubusercontent.com/8662695/34402599-8b9e88c2-ebdd-11e7-8ce0-65b137eb094c.png)
