### ISSUE TITLE
"服务器失效转移"

### ISSUE THREAD

**Issue by rocky-luo** [ihaolin/antares#13]
> 服务器失效转移：当服务器集群中某个节点宕机时，其正在调度的任务将转移到其他节点去调度；

是否可以理解为：所有任务是平均分配到server中的，一旦其中一个server宕机了，其他server会接管宕机的server的任务，如果这个宕机的server恢复了，其他server又会把任务还给这个server？
如果是这样的话，这个分布式算法太牛逼了，求教怎么做到的

**Comment by ihaolin** [comment]
+ 现在任务是在创建时，随机分配到一个server；
+ 如果宕机的server恢复了，并不会把之前的任务分配回去，这里只是保证任务能继续被调度。
