### ISSUE TITLE
关于job的编写

### ISSUE THREAD

**Issue by telltime** [ihaolin/antares#2]
job写好后放在哪里，是要重新编译程序吗

**Comment by ihaolin** [comment]
这随你的java应用启动就行，最好和业务应用分开，可以看下单元测试或者[antares-demo](https://github.com/ihaolin/antares/tree/master/antares-demo)。

**Comment by telltime** [comment]
那我在控制台怎么调用这个脚本   编译后直接放到lib目录吗   还是把脚本加到antares-tower.jar文件里面去

**Comment by ihaolin** [comment]
不是，先启动好server，再启动tower，在tower里配置你客户端应用里的job，配置完成后，再编写客户端应用(就是具体的job逻辑)，再启动你的客户端应用。

**Comment by telltime** [comment]
![gggggggggggggg](https://cloud.githubusercontent.com/assets/23161557/24091787/411c395c-0d85-11e7-82c4-5a2e4ffd15f3.jpg)

红框框的job已经写好了  我不知道要具体放到哪里才能让这个任务生效呢

**Comment by ihaolin** [comment]
就是在你自己的应用中先引入antares-client或antares-client-spring包，编写上面配置的job，然后启动你的应用就可以了。

**Comment by telltime** [comment]
还是不太懂  antares-client  在哪里，我只有server包 和 tower包

**Comment by ihaolin** [comment]
基于maven开发的项目都可以：

    <dependency>
        <groupId>me.hao0</groupId>
        <artifactId>antares-client</artifactId>
        <version>${version}</version>
    </dependency>

或者spring项目：

    <dependency>
        <groupId>me.hao0</groupId>
        <artifactId>antares-client-spring</artifactId>
        <version>${version}</version>
    </dependency>

**Comment by telltime** [comment]
如果我只是要分次执行多个shell命令，这种需要一个ScriptJob还是i需要写对应数目的ScriptJob

**Comment by ihaolin** [comment]
分次执行多个命令，你也可以用一个ScriptJob，然后作分片配置，1个分片配置一个命令。
